SensorService: don't contact batterystats service
Halium/android_frameworks_native pull request #6
Opened 2019-10-18 07:27 UTC by peat-psuwit

This service is normally in Java part. minimediaservice have a stub
implementation for this service, but some port may choose not to run it.

Change-Id: I20aa2f00d6f55ac14a77ad33bde10b51e26b9967

2020-02-03 21:16 UTC, luksus42 commented
I am not sure, if this breaks another functionality, but it fixes the wake lag issue on my FP2.

2020-02-04 10:56 UTC, Flohack74 requested changes

2020-02-04 10:56 UTC, Flohack74 commented on services/sensorservice/BatteryService.cpp
> +#if 0
If you disable code unconditionally then I see no point in keeping it around, I would vote for a simple delete. Dead code in either comments or disabled like this just bloats the project.

2020-02-04 11:04 UTC, peat-psuwit commented on services/sensorservice/BatteryService.cpp
> +#if 0
I leave it in to reduce potential conflicts when merging code from upstream, should the upstream modifies the code around here.

2020-02-04 22:00 UTC, Flohack74 commented on services/sensorservice/BatteryService.cpp
> +#if 0
Ok thats clever actually...

2020-02-04 22:00 UTC, Flohack74 approved these changes

2020-02-08 17:10 UTC, merged